### PR TITLE
Add support for emitting as a JSON object

### PR DESCRIPTION
**Pull request by czytelny**
just tiny switch to sending JSON

### CODE REVIEW

**Comment by amritb** [comment]
Thanks!

**Comment by czytelny** [comment]
No problem, I found your tool extremely useful. Would you mind if I make some more significant changes ? For example, I want to move emit functionality from modal window to main viewport and improve somehow sending that JSONs :)

**Comment by amritb** [comment]
Sounds great! But do test before making pull requests. I rarely work with socket.io now a days..

**Comment by czytelny** [comment]
No worries, testing it right away, because i'm going to use it a lot :)

**Pull request merged**
