### PR TITLE
upgrade socket.io to v3

### PR DESCRIPTION
**Pull request by le-yak**

### CODE REVIEW

**Review by nicolascav — APPROVED** [review]
I've tested an it works.

**Comment by le-yak** [comment]
Hello friend,
I'm sorry I forgot to provide some background information.
I was testing against a Socket.io v3 server and it just wouldn't connect (timeout). Upgrading the client to V3 fixed it. I have been using your client for testing my own project without an issue for about three weeks. Thanks for this very useful tool.

I'm trying to make some time to fix #28, no promises but this bug annoys me too ;)

**Comment by le-yak** [comment]
@nicolascav uh perhaps I should have RTFM.

https://socket.io/docs/v3/igrating-from-2-x-to-3-0/index.html

> due to several breaking changes, a v2 client will not be able to connect to a v3 server (and vice versa)

I haven't tested connecting to a V2 server, but they say it's not expected to work. You may want to revert this or pull a new branch :(

Sorry for this.

**Comment by amritb** [comment]
yeah good call - reverted. I should have tested this this personally. Thanks though. Maybe we add a drop down to select the version..

**Comment by nicolascav** [comment]
Oh, I apologize. I've tested with v3 client after hours trying make it run.

**Pull request merged**
