### PR TITLE
[Docker] Add a dockerfile

### LINKED ISSUE #18: Dockerfile
Hi @amritb, thanks for this tool!
We're going to add a quick Dockerfile for our uses. Created this issue for tracking, or to see if it was desired/undesired.
Would you like us to open a PR?

### PR DESCRIPTION
**Pull request by krumware**
This adds a dockerfile and includes instructions.

includes #19 
closes #18

### CODE REVIEW

**Comment by krumware** [comment]
@amritb I can update the instructions and consolidate the steps if you choose to host the image publicly on dockerhub, per the annotations in the readme

**Comment by krumware** [comment]
Just an extra comment here: I had a bit of trouble getting http-server to play nicely with routing behind a load balancer, but enhancements there can be another issue for another day. Doesn't affect the purposes of this PR.

**Comment by amritb** [comment]
Thanks for the PR @krumware ! Yeah I don't mind hosting this image. But few recommendations for the README: before you start explaining the steps, could you add something like:`You can use any server to try this tool - but in case you want to try with the server comes with this repo, here are the instruction to set up:?

**Comment by krumware** [comment]
Yup! I'll add those in the Command Line section

**Comment by krumware** [comment]
@amritb how does that look?

**Comment by amritb** [comment]
For load balancers, you might need to enable sticky sessions. Something like https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-sticky-sessions.html

**Comment by krumware** [comment]
I'm aware of that for the sockets, but I had trouble getting http-server (nginx underlying) to play nicely. 404 was being served regardless of the configuration I was trying with the routes. It's likely something that can be addressed with configuration, I just didn't have enough time to sink into it. Thanks for pulling!

**Pull request merged**
